name: sosmobil_rescue_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  signature: ^6.3.0

  # Pacotes principais da aplicação
  supabase_flutter: ^2.9.1
  shimmer: ^3.0.0
  provider: ^6.1.5
  url_launcher: ^6.3.1
  http: ^1.2.1

  # Pacotes para funcionalidades específicas
  image_picker: ^1.1.2
  pdf: ^3.10.8
  printing: ^5.12.0

  # Pacote de internacionalização (versão corrigida para ser compatível com flutter_localizations)
  intl: ^0.20.2 # CORREÇÃO FINAL: Atualizado para a versão exata que o SDK exige

  # Ícones
  cupertino_icons: ^1.0.8
  xml: ^6.5.0
  flutter_svg: ^2.2.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # PACOTES ADICIONADOS PARA IDENTIDADE VISUAL
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  # Dependências de desenvolvimento para o Isar (se voltar a usar)
  # build_runner: ^2.4.10
  # isar_generator: ^3.1.0+1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/car_diagram.png
    - assets/car_diagram.svg
    - assets/icon/icon.png
    - .env
    - assets/logo.png

# CONFIGURAÇÃO DO GERADOR DE ÍCONES
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

# CONFIGURAÇÃO DA SPLASH SCREEN
flutter_native_splash:
  color: "#18181B" # Cor de fundo da nossa UI
  image: assets/icon/icon.png

  # Configurações para Android 12+
  android_12:
    color: "#18181B"
    image: assets/icon/icon.png
